# Generated by Django 5.2.12 on 2026-03-29 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('volume', models.PositiveIntegerField(default=1000, help_text='Number of records per batch')),
                ('select_session', models.PositiveSmallIntegerField(default=1, help_text='Number of parallel session for reading')),
                ('target_session', models.PositiveSmallIntegerField(default=1, help_text='Number of parallel session for insert')),
                ('transfer_method', models.CharField(choices=[('direct', 'Direct Insert'), ('bcp', 'Bulk Copy'), ('inline', 'Same server')], default='direct', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('source', 'Source Database'), ('destination', 'Destination Database')], max_length=20, unique=True)),
                ('server', models.CharField(max_length=255)),
                ('database', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivalModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('last_archival_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='archival.application')),
            ],
            options={
                'unique_together': {('application', 'name')},
            },
        ),
        migrations.AddField(
            model_name='application',
            name='dstn_conn',
            field=models.ForeignKey(blank=True, limit_choices_to={'name': 'destination'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dstn_apps', to='archival.databaseconnection'),
        ),
        migrations.AddField(
            model_name='application',
            name='src_conn',
            field=models.ForeignKey(blank=True, limit_choices_to={'name': 'source'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_apps', to='archival.databaseconnection'),
        ),
        migrations.CreateModel(
            name='ArchivalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=200)),
                ('sequence', models.PositiveIntegerField(help_text='Execution order')),
                ('select_script', models.TextField(default='select * from', help_text='select script for source')),
                ('insert_script', models.TextField(default='insert into', help_text='insert script for destination')),
                ('delete_script', models.TextField(default='delete from', help_text='Delete script for destination')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='archival.archivalmodule')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('module', 'table_name')},
            },
        ),
    ]
