# Generated by Django 5.2.12 on 2026-03-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalmodule',
            name='last_archival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
