# Generated by Django 5.2.12 on 2026-03-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0002_alter_archivalmodule_last_archival_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseconnection',
            name='use_windows_auth',
        ),
    ]
