# Generated by Django 5.2.12 on 2026-04-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0002_application_created_at_application_max_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivaltable',
            name='acct_sum',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', help_text='Yes if account summary table?', max_length=1),
        ),
    ]
