# Generated by Django 5.2.12 on 2026-03-24 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0003_remove_databaseconnection_use_windows_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('volume', models.PositiveIntegerField(default=1000, help_text='Number of records per batch')),
                ('select_session', models.PositiveSmallIntegerField(default=1, help_text='Number of parallel session for reading')),
                ('target_session', models.PositiveSmallIntegerField(default=1, help_text='Number of parallel session for insert')),
                ('transfer_method', models.CharField(choices=[('direct', 'Direct Insert(Insert into ...)'), ('bcp', 'Bulk Copy'), ('inline', 'Same server with different DB')], default='direct', max_length=20)),
                ('dstn_conn', models.ForeignKey(limit_choices_to={'name': 'destination'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dstn_apps', to='archival.databaseconnection')),
                ('src_conn', models.ForeignKey(limit_choices_to={'name': 'Source'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_apps', to='archival.databaseconnection')),
            ],
        ),
        migrations.AddField(
            model_name='archivalmodule',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='archival.application'),
        ),
        migrations.AlterUniqueTogether(
            name='archivalmodule',
            unique_together={('application', 'name')},
        ),
    ]
