# Generated by Django 5.2.12 on 2026-04-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0003_archivaltable_acct_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivaltable',
            name='identity_insert',
            field=models.BooleanField(default=False, help_text='Enable identity insert for this table?'),
        ),
    ]
