# Generated by Django 5.2.12 on 2026-04-04 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0004_archivaltable_identity_insert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=150)),
                ('archival_date', models.DateField()),
                ('total_execution_time', models.FloatField(help_text='Total time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='archival.archivalmodule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivalTransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=200)),
                ('row_count', models.IntegerField(default=0)),
                ('execution_time', models.FloatField(help_text='Time in seconds')),
                ('archived_ids', models.TextField(blank=True, help_text='Comma-separated list of IDs (or range)', null=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='archival.archivaltransaction')),
            ],
        ),
    ]
