# Generated by Django 5.2.12 on 2026-03-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0004_application_archivalmodule_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='transfer_method',
            field=models.CharField(choices=[('direct', 'Direct Insert'), ('bcp', 'Bulk Copy'), ('inline', 'Same server')], default='direct', max_length=20),
        ),
    ]
