# Generated by Django 5.2.12 on 2026-03-24 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0005_alter_application_transfer_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dstn_conn',
            field=models.ForeignKey(blank=True, limit_choices_to={'name': 'destination'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dstn_apps', to='archival.databaseconnection'),
        ),
        migrations.AlterField(
            model_name='application',
            name='src_conn',
            field=models.ForeignKey(blank=True, limit_choices_to={'name': 'source'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_apps', to='archival.databaseconnection'),
        ),
    ]
