# Generated by Django 5.2.12 on 2026-04-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0005_archivaltransaction_archivaltransactiondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempArchivalIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=100)),
                ('module_id', models.IntegerField()),
                ('table_name', models.CharField(max_length=200)),
                ('archived_ids', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
