# Generated by Django 5.2.12 on 2026-04-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0006_temparchivalids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempArchivalIds',
        ),
        migrations.AlterField(
            model_name='application',
            name='transfer_method',
            field=models.CharField(choices=[('direct', 'Direct'), ('bcp', 'BCP'), ('inline', 'Inline')], default='inline', max_length=20),
        ),
    ]
