# Generated by Django 5.2.12 on 2026-03-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0006_alter_application_dstn_conn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivaltable',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='archivaltable',
            name='script',
        ),
        migrations.AddField(
            model_name='archivaltable',
            name='insert_script',
            field=models.TextField(default='insert into', help_text='insert script for destination'),
        ),
        migrations.AddField(
            model_name='archivaltable',
            name='select_script',
            field=models.TextField(default='select * from', help_text='select script for source'),
        ),
    ]
