# Generated by Django 5.2.12 on 2026-04-10 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0007_delete_temparchivalids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=200)),
                ('total_rows_inserted', models.IntegerField(default=0)),
                ('total_rows_merged', models.IntegerField(default=0)),
                ('total_rows_deleted', models.IntegerField(default=0)),
                ('total_time', models.FloatField(help_text='Total time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=150)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='archival.application')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='archival.archivalmodule')),
            ],
        ),
    ]
