# Generated by Django 5.2.12 on 2026-04-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0008_transactionsummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivaltransactiondetail',
            old_name='row_count',
            new_name='total_rows_inserted',
        ),
        migrations.AddField(
            model_name='archivaltransactiondetail',
            name='total_rows_deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='archivaltransactiondetail',
            name='total_rows_merged',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TransactionSummary',
        ),
    ]
