# Generated by Django 5.2.12 on 2026-04-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0009_rename_row_count_archivaltransactiondetail_total_rows_inserted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivaltransactiondetail',
            name='total_rows_archived',
            field=models.IntegerField(default=0),
        ),
    ]
