# Generated by Django 5.2.12 on 2026-04-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0011_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalmodule',
            name='status',
            field=models.CharField(default='nothing', help_text='nothing, in_progress, completed, failed', max_length=20),
        ),
    ]
