# Generated by Django 5.2.12 on 2026-04-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0012_archivalmodule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('VIEW', 'View'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('PROCESS', 'Process'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ERROR', 'Error')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
