# Generated by Django 5.2.12 on 2026-06-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0013_alter_auditlog_action_alter_auditlog_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseconnection',
            name='name',
        ),
    ]
