# Generated by Django 5.2.12 on 2026-06-10 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0014_remove_databaseconnection_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='T24Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=200)),
                ('select_script', models.TextField(default='select * from', help_text='select script for source')),
                ('insert_script', models.TextField(default='insert into', help_text='insert script for destination')),
                ('delete_script', models.TextField(default='delete from', help_text='Delete script for destination')),
                ('select_session', models.PositiveSmallIntegerField(default=1, help_text='Number of parallel session for reading')),
                ('insert_session', models.PositiveSmallIntegerField(default=1, help_text='Number of parallel session for insert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t24_tables', to='archival.application')),
            ],
            options={
                'unique_together': {('application', 'table_name')},
            },
        ),
    ]
