# Generated by Django 5.2.12 on 2026-06-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0015_t24table'),
    ]

    operations = [
        migrations.AddField(
            model_name='t24table',
            name='batch_size',
            field=models.PositiveIntegerField(default=1000, help_text='Number of records per batch'),
        ),
    ]
