# Generated by Django 5.2.12 on 2026-06-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0016_t24table_batch_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='name',
            field=models.CharField(choices=[('source', 'Source Database'), ('destination', 'Destination Database')], default='source', max_length=20),
            preserve_default=False,
        ),
    ]
