# Generated by Django 5.2.12 on 2026-06-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0017_databaseconnection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='name',
            field=models.CharField(choices=[('source', 'Source Database'), ('destination', 'Destination Database')], max_length=20, unique=True),
        ),
    ]
