# Generated by Django 5.2.12 on 2026-06-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0018_alter_databaseconnection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseconnection',
            name='name',
        ),
    ]
