# Generated by Django 5.2.12 on 2026-06-14 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0019_remove_databaseconnection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='t24table',
            name='archival_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
